site: 313yang.github.io
url: https://313yang.github.io
title: yangdev
description: Yang's development blog
googlewebfonts: Fira+Code:wght@400;500;700
twitter:
  username: Yang
  card: summary
  creator: Yang
author:
  twitter: Yang
  name: Yang
  avatar:
  email: #youremail
  url: https://313yang.github.io

baseurl: ""

highlighter: rouge

exclude:
  - .jekyll-cache

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
